defaluts: &defaults
  databases:
    process_admin:
      uri: "mongodb://localhost:27017/process_admin"

development:
  <<: *defaults
  uri: "mongodb://localhost:27017/dcrawler_dev"
  pool_size: 5

staging:
  <<: *defaults
  uri: "mongodb://localhost:27017/dcrawler_staging"
  pool_size: 5

production:
  <<: *defaults
  uri: "mongodb://localhost:27017/dcrawler_pro"
  pool_size: 5


